image: registry.gitlab.com/canya-com/gae-golang-build-container:0.4

variables:
  GOPATH: /go
  APP_PATH: $GOPATH/src/gitlab.com/$CI_PROJECT_PATH

before_script:
  - echo "+ perfoming build on alpine '`cat /etc/alpine-release`' with '`go version`'" 
  - echo "+ relocating cloned sources to $APP_PATH to satisfy go's package tree structure"
  - mkdir -p `dirname $APP_PATH`
  - mv /builds/$CI_PROJECT_PATH $APP_PATH
  - mkdir -p /builds/$CI_PROJECT_PATH
  - export GOPATH=$GOPATH
  - cd $APP_PATH 

after_script:
  - rm /tmp/$CI_PIPELINE_ID.json

stages:
  - deploy

deploy_staging:
  stage: deploy
  script:
    - echo "Deploy to staging server"
    - echo -n "+ current working path:" && pwd
    - echo $GCP_KEY > /tmp/$CI_PIPELINE_ID.json
    - echo $APP_YAML_BASE64 | base64 -d > ./app.yaml
    - gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
    - gcloud config set project $GCP_PROJECT_ID
    - go get
    - gcloud --quiet app deploy
    - gcloud app deploy cron.yaml
  environment:
    name: staging
  only:
  - master

deploy_prod:
  stage: deploy
  script:
    - echo "Deploy to production server"
      - echo -n "+ current working path:" && pwd
    - echo $GCP_KEY > /tmp/$CI_PIPELINE_ID.json
    - echo $APP_YAML_BASE64 | base64 -d > ./app.yaml
    - gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
    - gcloud config set project $GCP_PROJECT_ID
    - go get
    - gcloud --quiet app deploy
    - gcloud app deploy cron.yaml
  environment:
    name: production
  when: manual
  only:
  - master