
runtime: go
api_version: go1

env_variables:
  CANYA_SENDGRID_API_KEY: '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'
  CANYA_SENDGRID_TEMPLATE_ID: 'd-bd1327c67b294710aa2b5dcdfe0da944'

handlers:
- url: /.*
  script: _go_app